### ISSUE TITLE
JSON file item limit

### ISSUE THREAD

**Issue by perryraskin** [eyalzek/price-alert#3] opened 2017-03-17 18:39 UTC
This only works if the JSON file has 1-2 items maximum. If I try the code with more items (more product link IDs), then i get errors. Not sure what the solution is, or even what the error is saying.

Traceback (most recent call last):
  File "price-alert.py", line 99, in <module>
    main()
  File "price-alert.py", line 73, in main
    config = get_config(args.config)
  File "price-alert.py", line 57, in get_config
    return json.loads(f.read())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 12 column 9 (char 316)

Let me know if you have any idea, ill try to figure it out as well!

**Comment by eyalzek** [comment] 2018-01-28 00:14
Hey! I can't reproduce it locally with 4 items, so I think it might be something to do with your environment or the formatting of the file... Do you mind sharing your config file? Also, which environment are you running it on?

**Comment by perryraskin** [comment] 2018-01-28 05:09
lol this was so long ago, i have no idea, i think i ended up figuring it out tho

**Comment by eyalzek** [comment] 2018-01-28 12:28
Yeah I wasn't watching the repo and missed a couple of issues :)

Closing this, please open a new one if you face this again.

**Closed by eyalzek** 2018-01-28 12:28 UTC
